### ISSUE TITLE
نمایش فارسی و خروجی میلادی 

### ISSUE THREAD

**Issue by J-Arji** [peymayesh/PMCalendarView#1]
سلام  
تقویم خیلی خوبیه .ممنون که به اشتراک گذاشتید .
یه سوال داشتم امکانش هست که فارسینمایش بده (تقویم شمسی ) ولی خروجی رو میلادی ذخیره کنه ؟؟؟

**Comment by iAlirezaKML** [comment]
Hi @J-phantom
All data is stored as `NSDate` and you can format and print it in any calendar format using `NSDateFormatter`.
You can find very good information here:
http://www.codingexplorer.com/swiftly-getting-human-readable-date-nsdateformatter

**Comment by J-Arji** [comment]
بله ممنون پیداش کردم اما چطوری میشه اضافه کنم به پروژه تقویم رو ؟؟

**Comment by J-Arji** [comment]
در ضمن این آدرسی که دادید کار نمیکنه

**Comment by iAlirezaKML** [comment]
@J-phantom 
1- Copy `PMCalendarView` folder in you project folder.
2- Drag and drop `PMCalendarView.xcodeproj` to your project navigator in xcode.
3- Go to `General` tab in your project's target, from `Embedded Binaries` add `PMCalendarView.framework`.
4- Where you want use this library, add `import PMCalendarView`.

Link fixed. :D

**Comment by J-Arji** [comment]
آقا خیلی ممنون از شما :)
