### ISSUE TITLE
بستن بصورت خودکار

### ISSUE THREAD

**Issue by J-Arji** [peymayesh/PMCalendarView#2]
سلام دوباره  :)
چطور میشه وقتی یه تاریخی رو انتخاب کردی بعد بصورت خود کار بسته شود ؟
من تقویم را داخل یک باتن قرار داده ام 
ممنون میشم اگه راهنمای کنید  :)

```
@IBAction func startDateAction(sender: AnyObject) {
        self.view.addSubview(calendarView)
        calendarView.center = self.view.center  
    }
```

**Comment by iAlirezaKML** [comment]
Hi @J-phantom 

You should add `calendarView` to `self.view` in `viewDidLoad()`, then hide it.
Then on `startDateAction(_:)` unhide it and in `didSelectDate(_:_:)` function in delegate, hide it again.
